/*
Swagger Student Management System - OpenAPI 3.0

Testing CourseApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "//"
)

func Test_openapi_CourseApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CourseApiService AddCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CourseApi.AddCourse(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseApiService DeleteCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId int64

		resp, httpRes, err := apiClient.CourseApi.DeleteCourse(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseApiService GetCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId int64

		resp, httpRes, err := apiClient.CourseApi.GetCourse(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseApiService GetCourseList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CourseApi.GetCourseList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CourseApiService UpdateCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseId int64

		resp, httpRes, err := apiClient.CourseApi.UpdateCourse(context.Background(), courseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
